services:
  expo-dev:
    build: .
    container_name: expo-dev
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      # Zeego Cloud configuration
      ZEEGO_API_KEY: ${ZEEGO_API_KEY}
      # AWS configuration
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # Stripe configuration
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx expo start --dev-client
